"""empty message

Revision ID: 508710ba09b6
Revises: e454e104ded5
Create Date: 2020-06-15 14:15:21.639422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508710ba09b6'
down_revision = 'e454e104ded5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
